# Zomato Exercise

David Joshua Estrera, DATA100-S17

Zomato is a restaurant aggregator website. The platform provides information, menus and user-reviews of restaurants as well as food delivery options from partner restaurants in select cities. You have been provided 3 datasets:

- zomato.csv contains restaurant information like average_cost_for_two, cuisines
- location.csv contains location of the restaurants like address, city, locality & etc
- ratings.csv contains aggregate rating for each restaurant

The different files are connected using the `id` columns which can be found in the different files. The id column is a unique identifier to represent a restaurant. You can use this to **merge** the different files.

In [1]:
import pandas as pd
import numpy as np

1. Merge the zomato, location & ratings file into a signle dataframe and store it to the `merged_df` variable **(3pts)**

In [2]:
# Load the CSV files into separate DataFrames
zomato_df = pd.read_csv('zomato.csv')
location_df = pd.read_csv('location.csv')
ratings_df = pd.read_csv('ratings.csv')

merged_df = zomato_df.merge(location_df, on='id', how='inner') \
                     .merge(ratings_df, on='id', how='inner')

In [3]:
assert (6830, 35)==merged_df.shape

cols = ['id', 'address', 'city', 'city_id', 'country_id', 'latitude',
       'locality', 'locality_verbose', 'longitude', 'zipcode',
       'aggregate_rating', 'rating_color', 'rating_text', 'votes',
       'average_cost_for_two', 'book_url', 'cuisines', 'currency', 'deeplink',
       'events_url', 'featured_image', 'has_online_delivery',
       'has_table_booking', 'include_bogo_offers', 'is_book_form_web_view',
       'is_delivering_now', 'is_table_reservation_supported',
       'is_zomato_book_res', 'menu_url', 'mezzo_provider', 'name',
       'photos_url', 'price_range', 'thumb', 'url']

assert sorted(merged_df.columns) == sorted(cols)

2. Create a function that returns the average aggregate rating for each city. Expected returned value is a Series datatype which contains name of city as index and average aggregate rating as value. **(2pts)**

In [4]:
def exercise_2(merged_df):
    """
    This function calculates the average aggregate rating for each city.

    Args:
    merged_df (pd.DataFrame): The merged DataFrame containing city and aggregate rating data.

    Returns:
    pd.Series: A Series with city names as index and the average aggregate rating as values.
    """
    # Group by 'city' and calculate the mean of 'aggregate_rating'
    avg_rating_per_city = merged_df.groupby('city')['aggregate_rating'].mean()

    return avg_rating_per_city

In [5]:
res_series = exercise_2(merged_df)
assert True == np.isclose(3.302075, res_series[res_series.index == 'Pasay City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]
assert True == np.isclose(1.890741, res_series[res_series.index == 'Valenzuela City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]
assert True == np.isclose(1.558333, res_series[res_series.index == 'Malabon City'],
                          rtol=1e-05, atol=1e-08, equal_nan=False)[0]

3. Using the apply function of pandas convert the rating_text to a numeric equivalent. You are to introduce a new column in merged_df called `rating_numeric` which is based on the value from rating_text: **(3pts)**

Excellent = 5 <br>
Very Good = 4 <br>
Good = 3 <br>
Average = 2 <br>
Poor = 1 <br>
Not rated = 0 <br>

In [6]:
def convert_rating_text_to_numeric(rating_text):
    """
    This function converts the rating text to a corresponding numeric value.

    Args:
    rating_text (str): The rating text to be converted.

    Returns:
    int: The numeric equivalent of the rating text.
    """
    rating_mapping = {
        "Excellent": 5,
        "Very Good": 4,
        "Good": 3,
        "Average": 2,
        "Poor": 1,
        "Not rated": 0
    }
    return rating_mapping.get(rating_text, 0)  # Default to 0 if not rated

# Apply the conversion to the 'rating_text' column and create a new 'rating_numeric' column
merged_df['rating_numeric'] = merged_df['rating_text'].apply(convert_rating_text_to_numeric)

merged_df

,id,average_cost_for_two,book_url,cuisines,currency,deeplink,events_url,featured_image,has_online_delivery,has_table_booking,...,latitude,locality,locality_verbose,longitude,zipcode,aggregate_rating,rating_color,rating_text,votes,rating_numeric
0,6316125,1000,NaN,"Japanese, Ramen",P,zomato://restaurant/6316125,https://www.zomato.com/manila/mendokoro-ramenb...,https://b.zmtcdn.com/data/reviews_photos/971/2...,0,0,...,14.560313,Salcedo Village,"Salcedo Village, Makati City",121.024638,NaN,4.9,3F7E00,Excellent,1394,5
1,18409457,1300,NaN,"Korean, Grill, Korean BBQ",P,zomato://restaurant/18409457,https://www.zomato.com/manila/soban-k-town-gri...,https://b.zmtcdn.com/data/res_imagery/18290970...,0,0,...,14.552137,"Greenbelt 3, San Lorenzo, Makati City","Greenbelt 3, San Lorenzo, Makati City, Makati ...",121.021325,NaN,4.6,3F7E00,Excellent,602,5
2,6307689,1600,NaN,"American, Filipino",P,zomato://restaurant/6307689,https://www.zomato.com/manila/filling-station-...,https://b.zmtcdn.com/data/pictures/9/6307689/b...,0,0,...,14.563144,Poblacion,"Poblacion, Makati City",121.029800,1210.0,4.0,5BA829,Very Good,563,4
3,18581637,1000,NaN,Korean,P,zomato://restaurant/18581637,https://www.zomato.com/manila/romantic-baboy-t...,https://b.zmtcdn.com/data/reviews_photos/cc1/a...,0,0,...,14.633713,Tomas Morato,"Tomas Morato, Quezon City",121.035026,NaN,4.0,5BA829,Very Good,413,4
4,6315438,3000,NaN,"Seafood, American, Mediterranean, Japanese",P,zomato://restaurant/6315438,https://www.zomato.com/manila/niu-by-vikings-b...,https://b.zmtcdn.com/data/pictures/chains/8/63...,0,0,...,14.546236,"SM Aura Premier, Bonifacio Global City, Taguig...","SM Aura Premier, Bonifacio Global City, Taguig...",121.054365,NaN,4.6,3F7E00,Excellent,960,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6825,18635649,1000,NaN,"Deli, Filipino",P,zomato://restaurant/18635649,https://www.zomato.com/manila/trader-juans-fil...,NaN,0,0,...,14.422261,"Westgate Center, Filinvest City, Mutinlupa City","Westgate Center, Filinvest City, Mutinlupa Cit...",121.033175,NaN,2.9,FFBA00,Average,6,2
6826,6318581,400,NaN,Fast Food,P,zomato://restaurant/6318581,https://www.zomato.com/manila/jollibee-north-c...,http://b.zmtcdn.com/data/pictures/chains/0/630...,0,0,...,14.756424,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043329,NaN,3.0,CDD614,Average,5,2
6827,6318578,450,NaN,"Bakery, Filipino",P,zomato://restaurant/6318578,https://www.zomato.com/manila/goldilocks-north...,https://b.zmtcdn.com/data/res_imagery/6300003_...,0,0,...,14.756406,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043498,NaN,0.0,CBCBC8,Not rated,1,0
6828,6309612,1000,NaN,"American, Italian",P,zomato://restaurant/6309612,https://www.zomato.com/manila/red-buffalo-wing...,https://b.zmtcdn.com/data/res_imagery/6309612_...,0,0,...,14.610628,"Greenhills Town Center, Valencia, Quezon City","Greenhills Town Center, Valencia, Quezon City ...",121.037031,NaN,3.7,9ACD32,Good,96,3
6829,6318582,600,NaN,"Pizza, Fast Food",P,zomato://restaurant/6318582,https://www.zomato.com/manila/greenwich-north-...,https://b.zmtcdn.com/data/pictures/chains/2/63...,0,0,...,14.756382,"Zabarte Town Center, North Caloocan, Caloocan ...","Zabarte Town Center, North Caloocan, Caloocan ...",121.043452,NaN,0.0,CBCBC8,Not rated,2,0

In [7]:
assert 868 == merged_df[merged_df.rating_numeric == 0].shape[0]
assert True == ('rating_numeric' in merged_df.columns)

4. Create a function which filters the merged dataframe to only contain rows coming in from a specific city. Expected returned value is a dataframe **(2pts)**

In [8]:
def exercise_4(merged_df, city_name):
    """
    This function filters the merged DataFrame to only contain rows from a specific city.

    Args:
    merged_df (pd.DataFrame): The merged DataFrame that contains restaurant data including city.
    city_name (str): The name of the city to filter by.

    Returns:
    pd.DataFrame: A DataFrame containing only the rows where the city matches the city_name.
    """
    # Filter the dataframe based on the 'city' column
    filtered_df = merged_df[merged_df['city'] == city_name]

    return filtered_df

In [9]:

assert 'Makati City' == exercise_4(merged_df, 'Makati City').city.unique()[0]
assert (976, 36) == exercise_4(merged_df, 'Makati City').shape

assert 'Mandaluyong City' == exercise_4(merged_df, 'Mandaluyong City').city.unique()[0]
assert (443, 36) == exercise_4(merged_df, 'Mandaluyong City').shape

assert (0, 36) == exercise_4(merged_df, 'Quezon  City').shape

5. Create a function to filter the dataframe to only contain certain columns passed in the function. Expected returned value is a dataframe **(1pt)**

In [10]:
def exercise_5(merged_df, columns):
    """
    This function filters the DataFrame to only contain the specified columns.

    Args:
    merged_df (pd.DataFrame): The merged DataFrame containing multiple columns.
    columns (list): A list of column names to retain in the filtered DataFrame.

    Returns:
    pd.DataFrame: A DataFrame containing only the specified columns.
    """
    # Ensure the columns passed exist in the dataframe
    valid_columns = [col for col in columns if col in merged_df.columns]

    # Filter the dataframe to only contain the specified columns
    filtered_df = merged_df[valid_columns]

    return filtered_df

In [11]:
cols = ['name', 'cuisines', 'city', 'aggregate_rating']
assert sorted(cols) == sorted(exercise_5(merged_df, cols).columns)
assert (6830, 4) == exercise_5(merged_df, cols).shape

cols = ['average_cost_for_two', 'book_url', 'cuisines', 'currency', 'deeplink',
       'events_url', 'featured_image', 'has_online_delivery',
       'has_table_booking', 'include_bogo_offers', 'is_book_form_web_view']
assert sorted(cols) == sorted(exercise_5(merged_df, cols).columns)
assert (6830, 11) == exercise_5(merged_df, cols).shape

6.  What is the most common restaurant name in the dataset? **(2pts)** Write down your answer and show code used to come up with the answer.

In [13]:
# Find the most common restaurant name
most_common_restaurant = merged_df['name'].value_counts().idxmax()

print("Most common restaurant name:", most_common_restaurant)

Most common restaurant name: Starbucks

7. Which restaurant has the most expensive average cost for two? **(2pts)** Write down your answer and show code used to come up with the answer.

In [16]:
# Find the restaurant with the most expensive average cost for two
most_expensive_restaurant = merged_df.loc[merged_df['average_cost_for_two'].idxmax(), 'name']

print("Restaurant with the most expensive average cost for two:", most_expensive_restaurant)

Restaurant with the most expensive average cost for two: The Tasting Room

8. How many restaurants do not have a zipcode? **(1pt)** Write down your answer and show code used to come up with the answer.

In [17]:
# Count the number of restaurants without a zipcode
restaurants_without_zipcode = merged_df['zipcode'].isnull().sum()

print("Number of restaurants without a zipcode:", restaurants_without_zipcode)

Number of restaurants without a zipcode: 6713

9. How many restaurants in the dataset allow online delivery? **(1pt)** Write down your answer and show code used to come up with the answer.

In [20]:
# Count the number of restaurants that allow online delivery
restaurants_with_online_delivery = merged_df[merged_df['has_online_delivery'] == '1'].shape[0]

print("Number of restaurants that allow online delivery:", restaurants_with_online_delivery)

Number of restaurants that allow online delivery: 0

10. Which locatlity has more expensive food? Poblacion or Salcedo Village? **(3pts)** Write down your answer and show code used to come up with the answer.

In [22]:
# Filter the dataset for Poblacion and Salcedo Village
poblacion_cost = merged_df[merged_df['locality'] == 'Poblacion']['average_cost_for_two'].mean()
salcedo_village_cost = merged_df[merged_df['locality'] == 'Salcedo Village']['average_cost_for_two'].mean()

print(poblacion_cost, salcedo_village_cost)
# Compare the two localities
more_expensive_locality = 'Poblacion' if poblacion_cost > salcedo_village_cost else 'Salcedo Village'

print("Locality with more expensive food:", more_expensive_locality)

898.2142857142857 989.1025641025641
Locality with more expensive food: Salcedo Village